security:
    enable_authenticator_manager: true
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
        App\Security\User: auto

    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter : 'username'
                password_parameter : 'password'
            entry_point: form_login
            logout:
                path: logout
                target: login
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }