security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
        App\Security\User: auto

    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # TODO : Figure out how to force them to go to the login page
            anonymous: true
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter : 'username'
                password_parameter : 'password'
            logout:
                path: logout