index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

product:
    path: /product
    controller: App\Controller\ProductController::newProduct

sales:
    path: /sales
    controller: App\Controller\SalesController::sales

api_product:
    path: /api/product
    controller: App\Controller\API\ProductController::save
    methods: POST

api_sales:
    path: /api/sales
    controller: App\Controller\API\SalesController::data
    methods: GET