index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

product:
    path: /product
    controller: App\Controller\ProductController::newProduct

sales:
    path: /sales
    controller: App\Controller\SalesController::sales
